- name: '15'
  # renovate: datasource=docker depName=quay.io/lvh-images/kind
  kernel: '6.12-20250521.025913'
  kube-proxy: 'none'
  kpr: 'true'
  devices: '{eth0,eth1}'
  secondary-network: 'true'
  tunnel: 'disabled'
  lb-mode: 'dsr'
  ingress-controller: 'true'
  misc: 'bpfClockProbe=false,cni.uninstall=false,tls.secretsBackend=k8s,tls.secretSync.enabled=true,tunnelProtocol=geneve,loadBalancer.dsrDispatch=geneve'
  ciliumendpointslice: 'true'
